# application.yml
server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: web-project-gateway
  cloud:
    gateway:
      routes: # ??? ??
        - id: web-project-api # ???? ?? id??? ??? ???? ??
          predicates: # ??
            - Path=/api/** # api/ ?? ??? ????
          uri: lb://WEB-PROJECT-API # ??? ???? WEB-PROJECT-API? ??? ???? ??? ???.
          filters:
            # url ???
            # ?<???>? ?? ??? ???? ???? ??? ? ??? ??. ()? ??? ?? ?? -> segment? (.*)? ??
            # ??(,)? ???? ?? url? ??? url? ?????.
            # ?? ?? ??? ??? ${???}?? url ???? ?? / ?????? ?? ??.
            - RewritePath=/web-project-api/(?<segment>.*), /$\{segment}

